---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # v4.4.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 839ef35dc1d72bb6eceac9fa809f095e2edcd12b # 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/returntocorp/semgrep
    rev: 115a458c1e942ed484a33cdbf29616da4ada8b20 # v1.50.0
    hooks:
      - id: semgrep-ci
        # rulesets: https://semgrep.dev/explore
        # defaults ignores tests/
        # https://semgrep.dev/docs/ignoring-files-folders-code/#understanding-semgrep-defaults
        args:
          - --config=p/python
          - --config=p/default
          - --metrics=off
  - repo: https://github.com/PyCQA/bandit
    rev: ca4faf2f82a7c68a088100f8ba2b8e56f9bdcfe3 # 1.7.5
    hooks:
      - id: bandit
        args:
          - --configfile=pyproject.toml
        additional_dependencies:
          - bandit[toml]
  - repo: https://github.com/pycqa/isort
    rev: e44834b7b294701f596c9118d6c370f86671a50d # 5.12.0
    hooks:
      - id: isort
  # Formats toml, i.e. pyproject.toml
  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: 4ef242b660e0f7c7c953b9d8289e302c3f49bfbc # v0.8.1
    hooks:
      - id: taplo
        args:
          - --option=align_entries=true
          - --option=align_comments=true
          - --option=column_width=120
          - --option=reorder_keys=true
          - --option=reorder_arrays=true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ffb6a759a979008c0e6dff86e39f4745a2d9eac4 # v3.1.0
    hooks:
      - id: prettier
        types_or:
          - json
          - yaml
          - html
          - markdown
        args:
          - --print-width=120
          - --prose-wrap=always
          - --single-quote
