name: booleaning
on:
  workflow_dispatch:
    inputs:
      STRING_INPUT:
        required: true
        type: string
        default: foo
      NUMBER_INPUT:
        required: true
        type: number
        default: 10
      BOOLEAN_INPUT:
        required: true
        type: boolean
        default: false
jobs:
  booleaning:
    uses: ./.github/workflows/booleaning-called.yaml
    with:
      STRING_INPUT: ${{inputs.STRING_INPUT}}
      NUMBER_INPUT: ${{inputs.NUMBER_INPUT}}
      BOOLEAN_INPUT: ${{inputs.BOOLEAN_INPUT}}
