name: booleaning
on:
  workflow_dispatch:
    inputs:
      STRING_INPUT:
        required: false
        type: string
        default: ''
      # NUMBER_INPUT:
      #   required: true
      #   type: string
      #   default: '10'
      BOOLEAN_INPUT:
        required: true
        type: boolean
        default: false
jobs:
  booleaning:
    uses: ./.github/workflows/booleaning-called.yaml
    with:
      STRING_INPUT: ${{inputs.STRING_INPUT}}
      # NUMBER_INPUT: ${{toJSON(inputs.NUMBER_INPUT)}}
      # NUMBER_INPUT_AUTO: 10
      BOOLEAN_INPUT: ${{inputs.BOOLEAN_INPUT}}
      MULTILINE_INPUT: |
        FOO=bar
        BAZ=qux
      MULTISPACE_INPUT: --foo bar --baz qux
  grab_objects:
    uses: ./.github/workflows/upload_gh_obj.yaml
