name: booleaning
on:
  workflow_dispatch:
    inputs:
      MY_BOOLEAN:
        required: true
        type: boolean
jobs:
  booleaning:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Boolean: ${INPUT_MY_BOOLEAN}"
