name: Booleaning Caller
on:
  workflow_dispatch:
    inputs:
      STRING_INPUT:
        required: false
        type: string
        default: ''
      BOOLEAN_INPUT:
        required: true
        type: boolean
        default: false
jobs:
  booleaning:
    uses: ./.github/workflows/booleaning-called.yaml
    with:
      STRING_INPUT: ${{inputs.STRING_INPUT}}
      BOOLEAN_INPUT: ${{inputs.BOOLEAN_INPUT}}
      MULTILINE_INPUT: |
        FOO=bar
        BAZ=qux
      MULTISPACE_INPUT: --foo bar --baz qux
  grab_objects:
    uses: ./.github/workflows/upload_gh_obj.yaml
