name: Standalone Scripts
run-name: Standalone Scripts
on:
  - workflow_call
  - workflow_dispatch
  - pull_request
  - push
  - release
permissions:
  contents: read
jobs:
  run-reusable-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shared scripts
        uses: actions/checkout@v4
        with:
          path: workflow_scripts
          sparse-checkout: |
            .github/workflows/scripts
      - name: List files in shared scripts
        run: |-
          ls -R
      - name: Run Script
        run: |-
          bash workflow_scripts/.github/workflows/scripts/test.sh
