on: pull_request
permissions:
  contents: read
jobs:
  run-reusable-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shared scripts
        uses: actions/checkout@v4
        with:
          repository: FireTail-io/github-workflows
          path: workflow_scripts
          sparse-checkout: |
            .github/workflows/scripts
      - name: List files in shared scripts
        run: |-
          ls -R
      - name: Run Script
        run: |-
          bash .github/workflows/scripts/test.sh
