on:
  - workflow_call
env:
  dockerfile: build_setup/Dockerfile
  DOCKER_BUILDKIT: 1
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Env
        run: |
          cat <<HEREDOC >>${{ github.env }}
          PYTHON_VERSION=$(cat .github/PYTHON_VERSION)
          HEREDOC
      - name: Docker Build
        run: |
          docker build \
            --target test \
            --file ${{ env.dockerfile }} \
            --tag local_build:latest \
            --build-arg PYTHON_VERSION \
            .
      - name: Extract Artifact From Image
        run: |
          mkdir -p artifacts
          docker run --rm \
            --mount "type=bind,src=./artifacts,dst=/artifacts" \
            local_build:latest \
            cp -r artifacts/. /artifacts
      - name: Checksum Artifact
        run: |
          sha256sum artifacts/random_bytes.tgz >>artifacts/checksums
      - name: Upload Lambda Zip Artifact to Workflow Run
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: checksum
          path: artifacts/checksums
      - name: Upload Lambda Zip Artifact to Workflow Run
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: random_bytes.tgz
          path: artifacts/random_bytes.tgz
