on:
  - workflow_call
env:
  dockerfile: build_setup/Dockerfile
  DOCKER_BUILDKIT: 1
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Env
        run: |
          cat <<HEREDOC >>${{ github.env }}
          PYTHON_VERSION=$(cat .github/PYTHON_VERSION)
          HEREDOC
      - name: Docker Build
        run: |
          docker build \
            --target test \
            --file ${{ env.dockerfile }} \
            --tag local_build:latest \
            --build-arg PYTHON_VERSION \
            .
