# Requires a .github/release-drafter.yml file
# https://github.com/release-drafter/release-drafter#example
name: Draft Release
run-name: '@${{ github.triggering_actor }}: ${{ github.ref_name }}'
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@65c5fb495d1e69aa8c08a3317bc44ff8aabe9772 # v5.24.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
