name: Get Commands: Name
run-name: Get Commands: Run Name
on: pull_request
# permissions: read-all
jobs:
  get-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Get Commands
        run: compgen -c
      - name: Get Aliases
        run: compgen -a
