name: Log GitHub Stuff
run-name: Log GitHub Stuff
on:
  - workflow_call
  - workflow_dispatch
  - pull_request
  - push
  - release
jobs:
  log_stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Log Environment Variables
        if: always()
        continue-on-error: true
        run: |
          env | sort
      - name: Log GitHub Object
        if: always()
        continue-on-error: true
        run: |
          jq --color-output '.' <<<'${{ toJson(github) }}'
      - name: Log Other Objects
        if: always()
        continue-on-error: true
        run: |-
          set +o errexit
          jq --color-output '.' <<<'${{toJSON(env)}}'
          jq --color-output '.' <<<'${{toJSON(vars)}}'
          jq --color-output '.' <<<'${{toJSON(job)}}'
          jq --color-output '.' <<<'${{toJSON(steps)}}'
          jq --color-output '.' <<<'${{toJSON(runner)}}'
          jq --color-output '.' <<<'${{toJSON(secrets)}}'
          jq --color-output '.' <<<'${{toJSON(needs)}}'
          jq --color-output '.' <<<'${{toJSON(inputs)}}'
