name: Log GitHub Stuff
run-name: Log GitHub Stuff
on:
  - workflow_call
  - workflow_dispatch
  - pull_request
  - push
  - release
jobs:
  log_stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Log Environment Variables
        if: always()
        continue-on-error: true
        run: |
          env | sort
      - name: Log GitHub Object
        if: always()
        continue-on-error: true
        run: |
          yq . \
            --prettyPrint \
            --input-format json \
            --colors \
            <<<'${{ toJson(github) }}'
