---
name: matrix
run-name: matrix
on:
  push:
    branches:
      - dev
jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        top:
          - key: key-1
            value: value-1
          - key: key-2
            value: value-2
    steps:
      - name: Print
        env:
          a: ${{matrix.top.key}}
          b: ${{matrix.top.value}}
        run: |-
          echo "a: ${b}"
          echo "b: ${b}"
