---
name: matrix
run-name: matrix
on:
  push:
    branches:
      - dev
jobs:
  getter:
    outputs:
      OUTPUT: ${{ steps.getter.outputs.OUTPUT}}
    runs-on: ubuntu-latest
    steps:
      - name: getter
        id: getter
        run: |-
          cat <<HEREDOC >>"${GITHUB_OUTPUT}"
          OUTPUT=[{"key":"key_a","value":"1"},{"key":"key_b","value":"2"},{"key":"key_c","value":"3"}]
          HEREDOC
  matrix:
    needs: getter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        top: ${{fromJson(needs.getter.outputs.OUTPUT)}}
    steps:
      - name: Print
        env:
          a: ${{matrix.top.key}}
          b: ${{matrix.top.value}}
        run: |-
          echo "a: ${a}"
          echo "b: ${b}"
