---
name: matrix
run-name: matrix
on:
  push:
    branches:
      - dev
jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a:
          - 1
          - 2
          - 3
        b:
          - 4
          - 5
          - 6
    steps:
      - name: Print
        env:
          a: ${{matrix.a}}
          b: ${{matrix.b}}
        run: |-
          echo "a: ${b}"
          echo "b: ${b}"
