name: Get pip Licenses
run-name: Get pip Licenses
defaults:
  run:
    shell: bash
env:
  WATCH_FILE: requirements.txt
  COMMIT_FILE: LICENSES.md
  SCRIPT: .github/pip-licenses.sh
  PY_BUILD_DEPS_FILE: requirements.txt
on: pull_request
jobs:
  generate_python_licenses_file:
    # Permission needed for committing license file
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.base_ref }}
      - name: Set Up Diffing
        # diff fails if no switch/checkout between diffed branches
        run: |
          git pull --verbose
          git checkout "${GITHUB_HEAD_REF}"
      - name: 'Set Condition: WATCH_FILE_CHANGED_IN_PR'
        run: |
          git diff --exit-code --name-status "${GITHUB_HEAD_REF}..${GITHUB_BASE_REF}" -- "${WATCH_FILE}" ||
            WATCH_FILE_CHANGED_IN_PR=true
          echo "WATCH_FILE_CHANGED_IN_PR=${WATCH_FILE_CHANGED_IN_PR:-false}" >>"${GITHUB_ENV}"
      - name: Setup Python Version and Caching
        if: fromJson(env.WATCH_FILE_CHANGED_IN_PR)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: If WATCH_FILE_CHANGED_IN_PR, Run License File Generator Script
        # Need fromJson to cast true/false string to boolean
        if: fromJson(env.WATCH_FILE_CHANGED_IN_PR)
        # Create two environments to exclude pip-licenses dependencies from output
        run: |
          environments=(
            build-depencies-env
            pip-licenses-env
          )
          echo "${environments[0]}" | tr "[:lower:]" "[:upper:]"
          python3 -m venv "${environments[0]}"
          source "${environments[0]}/bin/activate"
          pip install -r "${PY_BUILD_DEPS_FILE}"
          deactivate
          echo "${environments[1]}" | tr "[:lower:]" "[:upper:]"
          python3 -m venv "${environments[1]}"
          source "${environments[1]}/bin/activate"
          pip install pip-licenses
          {
            echo -e "# Software Licenses for Build Dependencies of the ${GITHUB_REPOSITORY} Repository\n" &&
              echo -e "Generated with [\`pip-licenses\`](https://pypi.org/project/pip-licenses/) on $(date -u +%F)\n" &&
              pip-licenses \
                --python="./${environments[0]}/bin/python3" \
                --from=mixed \
                --order=license \
                --format=markdown &&
              echo -e "\n## Summary\n" &&
              pip-licenses \
                --python="./${environments[0]}/bin/python3" \
                --from=mixed \
                --order=license \
                --format=markdown \
                --summary
          } >"${COMMIT_FILE}"
          status=$?
          deactivate
          rm -fr "${environments[@]}"
          cat "${COMMIT_FILE}"
          exit $status
      - name: 'Set Condition: COMMIT_FILE_CHANGED_IN_WORKFLOW'
        run: |
          git diff --exit-code --name-status -- "${COMMIT_FILE}" || 
            COMMIT_FILE_CHANGED_IN_WORKFLOW=true
          echo "COMMIT_FILE_CHANGED_IN_WORKFLOW=${COMMIT_FILE_CHANGED_IN_WORKFLOW:-false}" >>"${GITHUB_ENV}"
      - name: If COMMIT_FILE_CHANGED_IN_WORKFLOW, Commit and Push
        if: fromJson(env.COMMIT_FILE_CHANGED_IN_WORKFLOW)
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add --verbose "${COMMIT_FILE}"
          printf -v commit_msg "Update license file with new build dependencies\n\n
          [Link to bot repo](https://github.com)"
          echo "${commit_msg}"
          git commit --verbose --message="${commit_msg}"
          git push --verbose origin "${GITHUB_HEAD_REF}"
