name: Get pip Licenses
run-name: ${{ github.actor }} is getting pip licenses
on: [pull_request]
jobs:
  Output-Python-Licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Print The Environment
        run: printenv

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate License File Name
        run: |
          LICENSE_FILE=$(basename ${GITHUB_REPOSITORY})-pip-licenses.md
          echo "LICENSE_FILE=${LICENSE_FILE}" >>"${GITHUB_ENV}"

      - name: Run License File Script
        run: ./pip-licenses.sh "${LICENSE_FILE}"
        env:
          LICENSE_FILE: ${{ env.LICENSE_FILE }}

      - name: Update Pull Request With File
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout "${GITHUB_HEAD_REF}"

          git add "${LICENSE_FILE}"
          git commit -m "Update license file"
          git push

        env:
          LICENSE_FILE: ${{ env.LICENSE_FILE }}
