name: Get pip Licenses
run-name: Get pip Licenses
defaults:
  run:
    shell: bash
env:
  PY_DEPS_FILE: requirements.txt
on: pull_request
jobs:
  generate_python_licenses_file:
    # Permission needed for committing license file
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Do git stuff
        run: |
          git config --list
          git branch --verbose
          git pull --verbose
          git checkout ${GITHUB_BASE_REF}

          echo "git diff --exit-code --name-only ${GITHUB_HEAD_REF}..${GITHUB_BASE_REF} -- ${PY_DEPS_FILE}"

          if git diff --exit-code --name-only ${GITHUB_HEAD_REF}..${GITHUB_BASE_REF} -- ${PY_DEPS_FILE}; then
            echo "no change"
          else
            echo "yes change"
          fi

      # - run: |
      #     printenv
      #     ((TRIGGER_FILE_CHANGED)) && echo "yes"
      #     ((TRIGGER_FILE_CHANGED)) || echo "no"
