name: Get pip Licenses
run-name: Get pip Licenses
defaults:
  run:
    shell: bash
env:
  PY_DEPS_FILE: requirements.txt
on: pull_request
jobs:
  generate_python_licenses_file:
    # Permission needed for committing license file
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        # ref: ${{ github.head_ref }}
      - name: Do git stuff
        run: |
          git branch --verbose | xargs -t
          git pull --verbose | xargs -t
          git checkout --verbose GITHUB_HEAD_REF | xargs -t
          git checkout --verbose GITHUB_BASE_REF | xargs -t

          result='no change' | xargs -t
          git diff --exit-code --name-only GITHUB_HEAD_REF..$GITHUB_BASE_REF -- $PY_DEPS_FILE || result='change' | xargs -t
          echo "$result" | xargs -t
