name: Get pip Licenses
run-name: ${{ github.actor }} is getting pip licenses
on: [push]
jobs:
  Output-Python-Licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Print The Environment
        run: printenv
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Generate Output Filename
        # Remove all chars before last slash
        run: |
          LICENSE_FILE="${GITHUB_REPOSITORY}-pip-licenses.md"
          LICENSE_FILE="${license_file##*/}"
          echo "LICENSE_FILE=${LICENSE_FILE}" >> "$GITHUB_ENV"
      - name: Run pip-licenses.sh
        run: bash ./pip-licenses.sh ${{ env.LICENSE_FILE }}
