name: Get pip Licenses
run-name: ${{ github.actor }} is getting pip licenses
on: [pull_request]
jobs:
  Output-Python-Licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Print The Environment
        run: printenv
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Generate Output Filename
        shell: bash
        run: |
          LICENSE_FILE=$(basename ${GITHUB_REPOSITORY})-pip-licenses.md
          echo "LICENSE_FILE=${LICENSE_FILE}" >>"$GITHUB_ENV"
      - name: Generate License File
        run: /bin/bash ./pip-licenses.sh "${{ env.LICENSE_FILE }}"
      - name: Update Pull Request With File
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add "${{ env.LICENSE_FILE }}"
          git commit -m "Update license file"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
