name: Get pip Licenses
run-name: Get pip Licenses
defaults:
  run:
    shell: bash
env:
  WATCH_FILE: requirements.txt
on: pull_request
jobs:
  generate_python_licenses_file:
    # Permission needed for committing license file
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Set WATCH_FILE_CHANGED_IN_PR
        run: |
          git pull --verbose
          git checkout "${GITHUB_BASE_REF}"

          git diff --exit-code --name-status "${GITHUB_HEAD_REF}..${GITHUB_BASE_REF}" -- "${WATCH_FILE}" ||
            WATCH_FILE_CHANGED_IN_PR=1

          echo "WATCH_FILE_CHANGED_IN_PR=${WATCH_FILE_CHANGED_IN_PR:-0}" >>${GITHUB_ENV}

      - run: |
          printenv
          ((WATCH_FILE_CHANGED_IN_PR)) && echo "yes"
          ((WATCH_FILE_CHANGED_IN_PR)) || echo "no"
