name: Run on Comment
on:
  issue_comment:
    types: 
      - created
      - edited
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'magic string')
    steps:
      # - name: Get PR Branch
      #   uses: xt0rted/pull-request-comment-branch@v2
      #   id: get-pr-branch
      - name: Checkout PR branch
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ steps.get-pr-branch.outputs.head_ref }}
      - run: git branch
      # - name: Comment back
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: "👋 It's magic!"
      #       })