name: Run on Comment
on:
  issue_comment:
    types: 
      - created
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'magic string')
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
      - run: git branch
