name: 'PR Created/Updated: Docker'
run-name: ${{ github.event_name }} | @${{ github.actor }} | ${{ github.head_ref }}
on:
  - pull_request
permissions: write-all
defaults:
  run:
    shell: bash
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0
      - name: Build and push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
        with:
          target: image
          tags: something
          file: Dockerfile
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image
      - name: Get Images
        run: docker images