---
name: Pre-Commit
run-name: Pre-Commit
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # At 47 minutes past the hour, every 8 hours, starting at 01:00 AM
    - cron: '47 1/8 * * *'
  workflow_dispatch:
jobs:
  pre-commit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        # with:
        #   sparse-checkout-cone-mode: false
        #   sparse-checkout: |
        #     README.md
        #     requirements.txt
      - name: Setup Python Version and Cache Pip Packages
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.11'
          cache: pip
      - name: Setup Pre-Commit Hook Cache and Run On All Files
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 #v3.0.0
