on:
  - pull_request
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Build
        uses: ./.github/workflows/docker_build.yml
