---
name: GitHub Object Grabber
run-name: 'GitHub Object Grabber: ${{github.event_name}}, ${{github.ref_type}}'
on:
  pull_request:
    branches:
      - dev
  push:
    branches: 
      - main
      - dev
    tags:
      - v*
  release:
    types: 
      - prereleased
      - released
  workflow_call:
    inputs:
      call_slug:
        type: string
        required: false
  workflow_dispatch:
    inputs:
      dispatch_slug:
        type: string
        required: false
permissions: 
  actions: none
  checks: none
  contents: none
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
env:
  GH_TOKEN: ${{github.token}}
jobs:
  grab:
    runs-on: ubuntu-latest
    env:
      OBJ_NAME: ${{format('{0}{1}-', inputs.dispatch_slug, inputs.call_slug)}}${{github.event_name}}-${{github.ref_type}}-github-context.json
    steps:
      - name: Dump GitHub Object JSON
        run: |
          cat <<HEREDOC >${{env.OBJ_NAME}}
          ${{toJson(github)}}
          HEREDOC
      - name: Upload GitHub Object JSON
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.OBJ_NAME}}
          path: ${{env.OBJ_NAME}}
