name: PR Event Grabber
on: pull_request
permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Event
        uses: actions/upload-artifact@v3
        with:
          name: pr_event_payload
          path: ${{ github.event_path }}
