name: GitHub Object Grabber
run-name: 'GitHub Object Grabber: ${{ github.event_name }}'
on: 
  - pull_request
  - push
  - release
permissions:
  contents: read
  issues: write
  pull-requests: write
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Object JSON
        run: |
          echo '${{ toJson(github) }}' | jq '.token = "****"' >github_${{ github.event_name }}_context.json
      - name: Upload GitHub Object JSON
        uses: actions/upload-artifact@v3
        with:
          name: github_${{ github.event_name }}_context.json
          path: github_${{ github.event_name }}_context.json
